name: Test awsdocs/aws-doc-sdk-examples-tools

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  pytest:
    name: Lint (black) all files
    runs-on: ubuntu-latest
    steps:
      - name: checkout contents
        uses: actions/checkout@v3
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: run black
        run: python -m black --check **/*.py
      - name: run mypy
        run: python -m mypy aws_doc_sdk_examples_tools
